name: activity8
description: "A new Flutter project."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.18  # Keep only one entry for audioplayers
  animated_widgets: ^1.1.0  # For animations
  lottie: ^1.3.0  # Optional for high-quality animations
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/spooky_music.mp3
    - assets/sounds/jumpscare.mp3
    - assets/sounds/success_sound.mp3
    - assets/images/ghost.jpeg
    - assets/images/pumpkin.jpeg
    - assets/images/trap.jpeg
    - assets/images/background.jpeg

    